### PR TITLE
Fix perplexity Inf for Celda_CG.reslist. Fix #112

### LINKED ISSUE #112: Optimize calculate_perplexity function
calculate_perplexity function generates Inf for very large completeLogLik. Can skip taking exp first then log by doing log(1) - mean(completeLogLik)

### PR DESCRIPTION
**Pull request by 87875172**

### CODE REVIEW

**Comment by definitelysean** [comment]
@87875172 I think you need to add some additional documentation to calculate_perplexity() for the log parameter to make the build happy. Here's the key part of the log:

```
Codoc mismatches from documentation object 'calculate_perplexity':
calculate_perplexity
  Code: function(completeLogLik, log = FALSE)
  Docs: function(completeLogLik)
  Argument names in code not in docs:
    log
```

**Comment by 87875172** [comment]
There are some errors with s3_generics.R. I think when I add the "log" parameter to visualize_performance_metric.celda_CG function I have to update this parameter in the s3_generics.R visualize_model_performance function. But visualize_performance_metric.celda_C and  visualize_performance_metric.celda_G does not have the "log" parameter, which causes inconsistency and warning in Travis tests. Should I add a "log" parameter to these two functions too even though they do not use this parameter?

checking S3 generic/method consistency ... WARNING
visualize_model_performance:
  function(celda.list, method, title, log)
visualize_model_performance.celda_C:
  function(celda.list, method, title)
visualize_model_performance:
  function(celda.list, method, title, log)
visualize_model_performance.celda_G:
  function(celda.list, method, title)

**Comment by definitelysean** [comment]
Hey @87875172 , you're correct, it's because those methods don't have the new log parameter. 
Can you refactor visualize_model_performance.celda_C and celda_G to use this parameter? They currently output log-scale plots too, so I think it makes sense.
This will also make this build error go away ;).

**Comment by definitelysean** [comment]
Sorry this took so long to merge @87875172 !

**Pull request merged**
